// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvaktymofdlffjmgipyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2YWt0eW1vZmRsZmZqbWdpcHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTYzMDgsImV4cCI6MjA2ODg3MjMwOH0.DN0HY94Y9fA_j6mH90sujNocYjY5i07N9wAqfgjNP7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});